version: "2"

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:12
    expose:
      - "5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  app:
    environment:
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      DJANGO_MANAGEPY_MIGRATE: "on"
      DEBUG: 1
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    links:
      - db:db
    ports:
      - "8000"
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 8000:80
    depends_on:
      - app
    
volumes:
   static_volume:
  
